### ISSUE TITLE
Loss of manual configuration settings functionality for List / ListProjectQueues

### ISSUE THREAD

**Issue by trinchan** [iron-io/iron_go3#28]
We are in the process of moving from v2 to your v3 infrastructure. In our current system, we rely on loading a custom configuration based on our server environment. Our `.iron.json` looks like

```json
  "staging": {
    "project_id": "XXXXXX",
    "token": "XXXXXX",
    "port": 443,
    "protocol": "https",
    "host": "mq-aws-us-east-1-1.iron.io"
  },
  "dev": {
    "project_id": "XXXX",
    "token": "XXXXXX",
    "port": 443,
    "protocol": "https",
    "host": "mq-aws-us-east-1-1.iron.io"
  }
```

and we load the configuration based on an environment variable containing the environment name.

In v2, when we listed the queues, we used [ListProjectQueues](https://github.com/iron-io/iron_go/blob/master/mq/mq.go#L108) (using [ListSettingsQueues](https://github.com/iron-io/iron_go/blob/master/mq/mq.go#L80) underneath), which allows specifying the project id and token.

In v3, the corresponding [List](https://github.com/iron-io/iron_go3/blob/master/mq/mq.go#L144) and [ListPage](https://github.com/iron-io/iron_go3/blob/master/mq/mq.go#L151) functions do not have a way to specify a manual configuration. It calls [config.Config("iron_mq"](https://github.com/iron-io/iron_go3/blob/master/mq/mq.go#L170) underneath, loading the default config.

Are ListProjectQueues/ListSettingsQueues gone for good? Any plans to add them to the v3 library?

Thanks!

**Comment by rdallman** [comment]
seems like just an oversight in porting things over. will make a ticket for this but if it's blocking for y'all and urgent then we do gladly accept patches (should be copying code from iron_go to iron_go3 mostly). thanks for raising the issue.
