### ISSUE TITLE
Unhelpful error messages

### ISSUE THREAD

**Issue by Supermighty** [iron-io/iron_go3#32]
Received unhelpful error when connecting to an IronMQ from an IronWorker. Using p.PushStrings() for code package that does not include the iron.json file results in `panic: 301 Moved Permanently: EOF` error.  The error should be a permission denied error; something to indicate that the iron.json information is not available. 

Steps to reproduce
1. zip up go binary all by itself
2. upload
3. queue tasks
4. watch it error with 301

**Comment by rdallman** [comment]
thanks. I just want to add an error after the configuration is set if token or project_id are still empty (in `iron_go3`).
